
* NixOS and Home Manager Configuration

** Overview
This repository contains my personal NixOS and Home Manager configurations.
It's structured as a Nix Flakes repository to ensure reproducible builds and easy
management of my system and user-level settings.

** Structure
- /system.nix/: Contains the system-wide NixOS configuration.
- /home.nix/: Holds the user-specific configuration managed by Home Manager.
- /flake.nix/: The central flake file defining inputs and outputs for NixOS and Home Manager.

** Usage

*** Prerequisites
- Nix with Flakes support enabled.

*** Applying NixOS Configuration
Run the following command to apply the system configuration:
#+BEGIN_SRC sh
cd !/dotfile_nix/system
sudo nixos-rebuild switch -I nixos-config=./configuration.nix
#+END_SRC
Replace /my-system/ with the appropriate label for your system configuration as defined in /flake.nix/.

*** Install [[https://nix-community.github.io/home-manager/index.html][Home Manager]]
Run:
#+begin_src bash
cd ~/dotfiles_nix
nix build .#homeConfigurations.spiros.activationPackage
#+end_src

This will create the file `./result/activate` that can then be executed to install home-manager into the user environment. This is persistent across shells and system reboots.

Install home manager:
#+begin_src bash
./result/activate
#+end_src

*** Applying Home Manager Configuration
To apply the Home Manager configuration for the user 'spiros', use:
#+BEGIN_SRC sh
home-manager switch --flake .
#+END_SRC

*** Clone dotfiles
Can now use GitHub CLI to clone dotfile repos
#+BEGIN_SRC sh
cd ~
gh repo auth login
gh repo clone dotfiles
gh repo clone vimfiles
#+END_SRC
*** Update nixos version

** Appendix
*** Setting up NixOS
**** Install git and vim
Edit config to install git and vim.
#+BEGIN_SRC sh
sudo nano /etc/nixos/configuration.nix
#+END_SRC
Add the options the packages install area.

~Optional if you want to copy ssh key with scp~
Also enable openssh by finding and uncommenting the line with the following config:
#+BEGIN_SRC sh
services.openssh.enable = true;
#+END_SRC

Also enable flakes by adding:
#+BEGIN_SRC sh
nix.settings.experimental-features = [ "nix-command" "flakes" ];
#+END_SRC

Save and close the file and install the updates with:
#+BEGIN_SRC sh
sudo nixos-rebuild switch
#+END_SRC
**** Set up ssh keys
Copy ssh keys to the system. Either by USB or scp.

Ensure key file permission are restrictive enough (required by ssh agent)
#+BEGIN_SRC sh
chmod 600 ~/.ssh/your_private_key
#+END_SRC

Load the key in to the agent
#+BEGIN_SRC sh
ssh-add ~/.ssh/your_private_key
#+END_SRC

**** Clone the config
Clone repos uhing ssh keys. This could be done with https if you are unable to get keys. The repos are public.
#+BEGIN_SRC sh
git clone git@github.com:smantzavinos/dotfiles.git
git clone git@github.com:smantzavinos/dotfiles_nix.git
git clone git@github.com:smantzavinos/vimfiles.git
git clone git@gitlab.com:smantzavinos/notes.git
#+END_SRC
**** 

