
* NixOS and Home Manager Configuration

** Overview
This repository contains my personal NixOS and Home Manager configurations.
It's structured as a Nix Flakes repository to ensure reproducible builds and easy
management of my system and user-level settings.

** Structure
- /system.nix/: Contains the system-wide NixOS configuration.
- /home.nix/: Holds the user-specific configuration managed by Home Manager.
- /flake.nix/: The central flake file defining inputs and outputs for NixOS and Home Manager.

** Usage

*** Prerequisites
- Nix with Flakes support enabled.

*** Applying NixOS Configuration
Run the following command to apply the system configuration:
#+BEGIN_SRC sh
cd !/dotfile_nix/system
sudo nixos-rebuild switch -I nixos-config=./configuration.nix
#+END_SRC
Replace /my-system/ with the appropriate label for your system configuration as defined in /flake.nix/.

*** Install [[https://nix-community.github.io/home-manager/index.html][Home Manager]]
Run:
#+begin_src bash
cd ~/dotfiles_nix
nix build .#homeConfigurations.spiros.activationPackage
#+end_src

This will create the file `./result/activate` that can then be executed to install home-manager into the user environment. This is persistent across shells and system reboots.

Install home manager:
#+begin_src bash
./result/activate
#+end_src

*** Applying Home Manager Configuration
To apply the Home Manager configuration for the user 'spiros', use:
#+BEGIN_SRC sh
home-manager switch --flake .
#+END_SRC

*** Clone dotfiles
Can now use GitHub CLI to clone dotfile repos
#+BEGIN_SRC sh
cd ~
gh repo auth login
gh repo clone dotfiles
gh repo clone vimfiles
#+END_SRC
